
<div class="content" >
<div class="header">

   <h1 class="page-title" >Transaction r&eacute;ussie</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Transactions</a> <span class="divider">/</span></li>
            <li class="active">transaction r&eacute;ssie</li>
        </ul>

        
 <br>
    <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h3 align="center">Transaction r&eacute;ussie et enregistr&eacute;e!</h3>
    </div>
    <div align="center">
    <div><p><?php $elements_facture=$this->elements_facture;?></p></div>
    <div>
    <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'transactions', 'action' => 'index'), null, true); ?>">
         &nbsp;OK&nbsp;   </a>
     <a target="_blank" class="btn btn-success" href="<?php echo $this->url(array('controller' => 'transactions', 'action' => 'printfacture'), null, true); ?>"><i class="icon-print"></i>Imprimer une facture </a>
     </div>
    </div>
    </div>
