<?php
$this->headTitle('Gestion des eleveurs');
$tableCategorie = new Application_Model_Categorie_DbTable();
$tableDaral = new Application_Model_Daral_DbTable();

$tableFarmer = new Application_Model_Farmer_DbTable();
$tableLocalite = new Application_Model_Localite_DbTable();
$tableTypeNotification = new Application_Model_TypeNotification_DbTable();
$tableUsers = new Application_Model_Users_DbTable();

$vals = $tableDaral->getDashStats();
$farmers = $tableDaral->getLastFarmers();
$notifications = $tableDaral->getLastNotifications();
$darals = $tableDaral->getLastDarals();




 
$tableLocalite2 = new Application_Model_Localite_DbTable_Localite();

 
$tableDepartement = new Application_Model_Departement_DbTable_Departement();

?>


<div class="content">

	<div class="header">


		<h1 class="page-title">TABLEAU DE BORD</h1>
	</div>

	<ul class="breadcrumb">

		<li class="active">Tableau de bord</li>
	</ul>
   
   
   
   
   
	<div class="container-fluid">
		<div class="row-fluid">


			<div class="row-fluid">

				<div class="alert alert-info">
					<strong>URGENCE SIGNALEE :: </strong>
					<blink style="color: RED;">
					
					<?php echo $vals[4]." dans la localit&eacute; de "; ?>
					<?php     $linkedRow = $tableLocalite->find($vals[5])->current();
									if ($linkedRow) {
										echo $linkedRow->getZodekenAutoLabel();
									} else {
										echo $vals[5], '';
									} ?>
									</blink>
									
				</div>

				<div class="block">

					<a href="#page-stats" class="block-heading" data-toggle="collapse">Derni&egrave;res Statistiques (nationales)
						</a>
					<div id="page-stats" class="block-body collapse in">

						<div class="stat-widget-container">
							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[0] ?></p>
									<p class="detail">Eleveurs inscrits</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[1] ?></p>
									<p class="detail">B&ecirc;tes</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[2] ?></p>
									<p class="detail">Notifications</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[3] ?></p>
									<p class="detail">Cas de vol</p>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>

			<div class="row-fluid">
				<div class="block span6">
					<a href="#tablewidget" class="block-heading" data-toggle="collapse">Derniers
						&eacute;leveurs inscrits
					</a>
					<div id="tablewidget" class="block-body collapse in">
						<!--  <table class="table table-bordered table-condensed "> -->
						<table class="table list" style="margin: auto;">
						

							<thead>
								<tr>

									<th style="text-align: center;">Identifiant</th>
									<th style="text-align: center;">Pr&eacute;nom</th>
									<th style="text-align: center;">Nom</th>
									<th style="text-align: center;">&nbsp;</th>
								</tr>
							</thead>

							<tbody>



							
							
							<?php foreach ($farmers as $farmer):  ?>	
								<tr>

									<td style="text-align: center;"><?php echo $farmer[1]; ?><!-- [1] = 'id_farmer' in array -->
									</td>
									<td style="text-align: center;"><?php echo $farmer[9]; ?><!-- [9] = 'firstname_farmer' in array -->
									</td>
									<td style="text-align: center;"><?php echo $farmer[10]; ?><!-- [10] = 'lastname_farmer' in array -->
									</td>
									<td style="text-align: center;"><a 
										title="Voir" 
										href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'displayfarmer', 'id' => $farmer[1]), null, true); ?>"><i
											class="icon-zoom-in"></i> </a>
									</td>

								</tr>
								
								
								
								
							     
					<?php  endforeach; ?>
							</tbody>
						</table>
						
					</div>
				</div>
				<div class="block span6">
					<a href="#widget_notif_container" class="block-heading"
						data-toggle="collapse">Derni&egrave;res notifications </a>
					<div id="widget_notif_container" class="block-body collapse in">
						<!--<table class="table table-bordered table-condensed "> -->
						<table class="table list" style="margin: auto;">
						
							<thead>
								<tr>
									<th style="text-align: center;">Identifiant</th>
									<!-- <th style="text-align: center;">Eleveur</th> -->
									<th style="text-align: center;">Localit&eacute;</th>
									<th style="text-align: center;">Date</th>
									<th style="text-align: center;">Type</th>
									
								</tr>
							</thead>

							<tbody>


							<?php foreach ($notifications as $notification):  ?>	
								<tr>

									<td style="text-align: center;"><?php echo $notification[0]; ?>
									</td>
									<!-- <td style="text-align: center;"><?php //echo $notification[1]; ?>
									</td> -->
									<td style="text-align: center;"><?php     $linkedRow = $tableLocalite->find($notification[2])->current();
									if ($linkedRow) {
										echo $linkedRow->getZodekenAutoLabel();
									} else {
										echo $notification[2], '';
									} ?><!-- [2] = 'id_localite' in array -->
									</td>
									<td style="text-align: center;"><?php echo $notification[3]; ?><!-- [3] = 'date' in array -->
									</td>
									<td style="text-align: center;"><?php     $linkedRow = $tableTypeNotification->find($notification[4])->current();
									if ($linkedRow) {
										echo $linkedRow->getZodekenAutoLabel();
									} else {
										echo $notification[4], ' ';
									} ?>
									</td>
									
								</tr>
								
								
								
								
							     
					<?php  endforeach; ?>
	</tbody>
						</table>

					</div>
				</div>
			</div>

			<div class="row-fluid">
				<div class="block span6">
					<div class="block-heading">
						
						 <a href="#widget2container" data-toggle="collapse">Derniers m&eacute;dias publi&eacute;s</a>
					</div>
					<div id="widget2container" class="block-body collapse in" >
						<table class="table list" style="margin: auto;">
							
								<thead>
									<tr>
										<th style="text-align: center;">Titre </th>
										<th style="text-align: center;">Langue </th>
										<th style="text-align: center;">Date</th>
										<th style="text-align: center;">Lien</th>
										<th style="text-align: center;">Maladie</th>
										<th style="text-align: center;"></th>
									</tr>
								</thead>
								<tbody>
									
								<?php 
								
								
								$tableLangue = new Application_Model_Langue_DbTable();
								$tableMaladie = new Application_Model_Maladie_DbTable();
								
								$tableMedia = new Application_Model_Media_DbTable();
								$gridSelect2 = $tableMedia->getDbSelectByParams(array());
								$paginator2 = Zend_Paginator::factory($gridSelect2);
								$paginator2->setItemCountPerPage(5)
								->setCurrentPageNumber(1);
								
								foreach ($paginator2 as $row): ?>
									<tr>
										<td><?php echo $row->titre; ?></td>
										<td><?php     $linkedRow = $tableLangue->find($row->langue)->current();
										if ($linkedRow) {
											echo $linkedRow->getZodekenAutoLabel();
										} else {
											echo $linkedRow->langue, ' (unlinked)';
										} ?>
										</td>
										<td><?php echo $row->date_insertion; ?></td>
										<td><?php echo $row->lien; ?></td>
										<td><?php     $linkedRow = $tableMaladie->find($row->maladie)->current();
										if ($linkedRow) {
											echo $linkedRow->getZodekenAutoLabel();
										} else {
											echo $linkedRow->maladie, ' (unlinked)';
										} ?>
										</td>
										<td style="text-align: left"><a title="Voir"
										href="<?php echo $this->url(array('controller' => 'media', 'action' => 'detail', 'id' => $row->id), null, true); ?>"><i
											class="icon-zoom-in"></i> </a></td>
									</tr>
									
									
									
									
<?php endforeach; ?>
    </tbody>
							
						</table>
					</div>
				</div>
				
				
				

				<div class="block span6">
				<div class="blockheading">
				<a href="#widget_daral_container" class="block-heading"
						data-toggle="collapse">
					Derniers Darals</a>
				</div>
					<div id="widget_daral_container" class="block-body collapse in" >
						
							<!-- <table class="table table-bordered table-condensed "> -->
							<table class="table list" style="margin: auto;">
							 
								<thead>
									<tr>
										<th style="text-align: center;">Num&eacute;ro Daral </th>
										<th style="text-align: center;">Localit&eacute; </th>
										<th style="text-align: center;">D&eacute;partement</th>
										<th style="text-align: center;">R&eacute;gion</th>
									</tr>
								</thead>
								<tbody>
								<?php foreach ($darals as $daral):  ?>	
								<tr>

									<td style="text-align: center;"><?php echo $dar=$daral[2]; ?>
									</td>
									
									<td style="text-align: center;"><?php echo $daral[1]; ?>
									</td>
									
									<td style="text-align: center;"><?php $departement=$tableLocalite2->getDepartement($daral[1]); echo $departement; ?>
									</td>
									<td style="text-align: center;"><?php $region=$tableDepartement->getRegion($departement); echo $region;?>
									</td>
								</tr>
								
								
								
								
							     
					<?php  endforeach; ?>	
								
   								 </tbody>
							</table>
						
						
					</div>
					</div>
				</div>
			</div>




		</div>
	</div>







