<?php
$search = $this->search;
?>
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>
<div class="content">	
	<div class="header">
	   <h1 class="page-title" >Liste des vid&eacute;os</h1>
	</div>
	<ul class="breadcrumb">
		<li><a href="#" class="black">M&eacute;diatheque</a><span class="divider">/</span></li>
		<li class="active" >R&eacute;sultat recherche pour : <?php echo $search ?></li>
	</ul>
	
	<div style="text-align:right;margin-right:2em;">
	<a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'media', 'action' => 'index'), null, true); ?>"> Toutes les videos</a>
	</div>
	
	<div style="margin-left:2em">
	<form method="get" action="<?php echo $this->url(array('controller' => 'media', 'action' => 'search'), null, true); ?>">
	<div>
	Recherche : 
	<input type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" />
	<input type="submit" value="Rechercher" />
	</div>
	</form>
	</div>
	
	
	<div class="container">
		<div class="row">
			<?php
				require_once 'Zend/Loader.php';
				Zend_Loader::loadClass('Zend_Gdata_YouTube');
				$yt = new Zend_Gdata_YouTube();
				$yt->setMajorProtocolVersion(2);
				$query = $yt->newVideoQuery();
				$query->setAuthor('daralproject');
				$query->setOrderBy('relevance');
				//*****format search string ******
				
				$search=preg_replace( '/\s+/', ' ', $search);
				$search =implode('+',explode(" ",$search));
				 
				//********************************
				$videoFeed = $yt->getVideoFeed("http://gdata.youtube.com/feeds/api/users/daralproject/uploads/?q='.$search.'");
				foreach ($videoFeed as $video) : $thumbs = $video->getVideoThumbnails();
				$count = 1;
				?>
					<div class="span4" style="height: 400px;">
						<div class="thumbnail">
							<h3 align="center"><?php echo $video->getVideoTitle(); ?></h3>
							<img src="<?php echo $thumbs[0]['url']; ?>">
							<br>
							<p align="center">
								<a href="<?php echo $this->url(array('controller' => 'media', 'action' =>'read', 'idVideo'=>$video->getVideoId()));?>" class="btn btn-info">
								<i class="icone-picture icon-white"></i>Voir cette video</a>
								<span class="label label-info"><?php echo round($video->getVideoDuration()/60); ?>min</span>
							</p>
						</div>
					</div>
				<?php 
				$count++;
				endforeach; 
				?>
		</div>
	</div>
</div>
