<?php
$tableFarmer = new Application_Model_Farmer_DbTable();
$tableLocalite = new Application_Model_Localite_DbTable();
$tableTypenotification = new Application_Model_Typenotification_DbTable();
$tableUsers = new Application_Model_Users_DbTable();
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>
<div class="content">	
<div class="header">
   <h1 class="page-title" >Historique des Notifications</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="<?php echo $this->url(array('controller' => 'daral', 'action' => 'index'), null, true); ?>" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li class="active">Historique des Notifications</li>
        </ul>

<div
	class="pull-right"><a class="btn btn-info"
	href="<?php echo $this->url(array('controller' => 'notification', 'action' => 'index'), null, true); ?>"><i
	class=" icon-refresh icon-white"></i> Actualiser</a> <!--  ****  changed 'action'=>'create' into 'action'=>'add' ***  -->
<a class="btn btn-success"
	href="<?php echo $this->url(array('controller' => 'notification', 'action' => 'create'), null, true); ?>"><i
	class="icon-plus icon-white"></i> Ajouter</a> <!--  ********************************************************** -->
</div>
<br />

<form method="get"
	action="<?php echo $this->url(array('controller' => 'notification', 'action' => 'index'), null, true); ?>">
<div>Rechercher: <input class="input-large search-query"
	placeholder="Mots cles..." type="text" name="_kw"
	value="<?php echo htmlspecialchars($this->param_kw); ?>" /> &nbsp dans
&nbsp <?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
  'all' => 'All',
  'id_farmer' => 'Eleveur',
  'id_localite' => ' Localite',
  'type' => 'Type',
  'id_user' => 'Utilisateur',
)); ?>&nbsp
<button class="btn" type="submit"><i class="icon-search"></i>Rechercher</button>
</div>
</form>

<form method="post"
	action="<?php echo $this->url(array('controller' => 'notification', 'action' => 'delete'), null, true); ?>"
	onsubmit="return confirm('Delete selected rows?');">
<table class="table table-bordered table-condensed ">
	<thead>
		<tr>
			<th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
			<th style="text-align: center;"
			<?php if ('id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
			<span class="label label-inverse">Identifiant <a
				href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'asc')); ?>'>&#x25B2;</a>
			<a
				href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'desc')); ?>'>&#x25BC;</a>
			</span></th>
			
			<th style="text-align: center;"
			<?php if ('id_localite' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
			<span class="label label-inverse">Localite <a
				href='<?php echo $this->url($_GET + array('_sf' => 'id_localite', '_so' => 'asc')); ?>'>&#x25B2;</a>
			<a
				href='<?php echo $this->url($_GET + array('_sf' => 'id_localite', '_so' => 'desc')); ?>'>&#x25BC;</a>
			</span></th>
			<th style="text-align: center;"
			<?php if ('date' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
			<span class="label label-inverse">Date <a
				href='<?php echo $this->url($_GET + array('_sf' => 'date', '_so' => 'asc')); ?>'>&#x25B2;</a>
			<a
				href='<?php echo $this->url($_GET + array('_sf' => 'date', '_so' => 'desc')); ?>'>&#x25BC;</a>
			</span></th>
			<th style="text-align: center;"
			<?php if ('type' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
			<span class="label label-inverse">Type <a
				href='<?php echo $this->url($_GET + array('_sf' => 'type', '_so' => 'asc')); ?>'>&#x25B2;</a>
			<a
				href='<?php echo $this->url($_GET + array('_sf' => 'type', '_so' => 'desc')); ?>'>&#x25BC;</a>
			</span></th>
			 <th style="text-align: center;" 
            <?php if ('description' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Description 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'description', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'description', '_so' => 'desc')); ?>'>&#x25BC;</a>
                
            </span></th>
		<?php if ($tableUsers->isAdmin() === TRUE){ ?>	<th>Actions</th><?php }?>
		</tr>
	</thead>

	<tbody>
	<?php foreach ($this->paginator as $row): ?>
		<tr>
			<td align="center"><input type="checkbox" name="del_id[]"
				value="<?php echo $row->id; ?>" /></td>
			<td align="right"><?php echo $row->id; ?></td>
			
			<td><?php     $linkedRow = $tableLocalite->find($row->id_localite)->current();
			if ($linkedRow) {
				echo $linkedRow->getZodekenAutoLabel();
			} else {
				echo $linkedRow->id_localite, ' (unlinked)';
			} ?></td>
			<td><?php echo $row->date; ?></td>
			<td><?php     $linkedRow = $tableTypenotification->find($row->type)->current();
			if ($linkedRow) {
				echo $linkedRow->getZodekenAutoLabel();
			} else {
				echo $linkedRow->type, ' (unlinked)';
			} ?></td>
			<td align="right"><?php echo $row->description; ?></td>
			<?php if ($tableUsers->isAdmin() === TRUE){ ?>
			<td style="text-align: left"><a title="Envoyer sms"
				href="<?php echo $this->url(array('controller' => 'notification', 'action' => 'sendsms', 'id' => $row->id, 'id_localite' => $row->id_localite, 'id_farmer' => $row->id_farmer, 'type' => $row->type), null, true); ?>"><i
				class="icon-mail-open"></i>
				</a>- <a title="Modifier"
				href="<?php echo $this->url(array('controller' => 'notification', 'action' => 'update', 'id' => $row->id), null, true); ?>"><i
				class="icon-pencil"></i></a> - <a title="Archiver"
				onclick="return confirm('Confirmez la suppression!');"
				href="<?php echo $this->url(array('controller' => 'notification', 'action' => 'delete', 'del_id' => $row->id), null, true); ?>"><i
				class="icon-trash"></i></a></td><?php }?>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<br />
<button class="btn btn-danger" type="submit"><i class=" icon-trash icon-white"></i> Supprimer</button></form>

		<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');?>
</div>