<div class="content">
<div class="header">
   <h1 class="page-title" >Cheptel</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Cheptel</a> <span class="divider">/</span></li>
            <li class="active">Photo animal</li>
        </ul>
 <div style="margin-left: 1em"><a class="btn btn-info" href="javascript:history.back();">Retour</a></div> 
 <div style="margin-left: 1em;margin-right:1em"> 
  
</div>
<?php
 $photo = $this->photo;
?>
<div style="margin-left:2em;">
<br/>
  <div style="margin-left:20em"><img src="<?php echo $this->baseUrl()?>/image/<?php echo $this->photo; ?>" width = "400 " height = "170 "  alt="photo" class ="thumbnail "/></div>


</div>
</div>