<?php
$tableFarmer = new Application_Model_Farmer_DbTable();
$tableAnimaltype = new Application_Model_Animaltype_DbTable();
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>
<script>

$(function (){
	   $(".pop").popover({placement:'left'}); 
	});
</script>
<div class="content">	
<div class="header">
   <h1 class="page-title" >Cheptel: liste des animaux </h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Cheptel</a> <span class="divider">/</span></li>
            <li class="active">Liste des animaux</li>
        </ul>
<div style="margin-left: 1em"><a class="btn btn-info" href="javascript:history.back();">Retour</a></div>  
<br/>        
<form>
<div style="margin-left: 1em; padding-bottom:0.5em;">
<a class="btn" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'recherche'), null, true); ?>"><i class="icon-search"></i>Rechercher</a>
<a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>"><i class=" icon-refresh icon-white"></i> Actualiser</a>
    <!--  ****  changed 'action'=>'create' into 'action'=>'add' ***  -->

</div>
</form>

<form method="post" action="<?php echo $this->url(array('controller' => 'animal', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<div style="margin-left:1em; margin-right:1em;">
<table width="100%" border="1" style="border-collapse:collapse" cellspacing="0" 
    cellpadding="3">
    <thead>
        <tr>
            
            <th<?php if ('id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">ID Animal
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('fk_id_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Identifiant Eleveur
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_id_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_id_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('fk_animaltype' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Type d'animal
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('photo_left' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">VUE GAUCHE
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_left', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_left', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('photo_right' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">VUE DROITE 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_right', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_right', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('photo_front' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">VUE FACE 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_front', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_front', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th><span class="label label-inverse">Signes particuliers</span></th>
            
        </tr>
    </thead>
    
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
           
            <td align="center"><?php echo substr($row->animal_id,9); ?></td>
            <td align="center"><?php echo $row->fk_id_farmer; ?></td>
            <td align="center"><?php echo $row->fk_animaltype; ?></td>
            <td align="center"><a class="black" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'displayanimal', 'photo' => $row->photo_left), null, true); ?>">VUE GAUCHE</a>-<a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'updatephotoleft', 'id' => $row->animal_id), null, true); ?>">
                                                                   <?php if ($row->photo_left == "no_photo.png"){?><i class="icon-plus" ></i><?php } else {?><i class="icon-pencil"></i><?php }?> </a></td>
            <td align="center"><a class="black" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'displayanimal', 'photo' => $row->photo_right),null, true); ?>">VUE DROITE</a>-<a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'updatephotoright', 'id' => $row->animal_id), null, true); ?>">
                                                                   <?php if ($row->photo_right == "no_photo.png"){?><i class="icon-plus" ></i><?php } else {?><i class="icon-pencil"></i><?php }?> </a></td>
            <td><a class="black" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'displayanimal', 'photo' => $row->photo_front),null, true); ?>">VUE FACE</a>-<a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'updatephotofront', 'id' => $row->animal_id), null, true); ?>">
                                                                   <?php if ($row->photo_front == "no_photo.png"){?><i class="icon-plus" ></i><?php } else {?><i class="icon-pencil"></i><?php }?></a></td>
            <td align="center"><a href="#" class="pop black" data-content="<?php echo $row->comment; ?> "data-original-title="Signes particuliers"><i class="icon-zoom-in"></i></a>&nbsp;-<a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'updatecomment', 'id' => $row->animal_id), null, true); ?>">
                                                                   <?php if ($row->comment == "R.A.S"){?><i class="icon-plus" ></i><?php } else {?><i class="icon-pencil"></i><?php }?> </a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table><br />
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');?>
</div>
</form>


</div>