<?php
$this->headTitle('Animal: recherche');
$tableAnimal = new Application_Model_Animal_DbTable();
$form = $this->form;
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}


</script>

<script>

$(function (){
	   $(".pop").popover({placement:'left',delay: { show: 10, hide: 10 },trigger: 'hover'}); 
	});
</script>
    


<div class = "content"  >
<div class="header">
  <h1 class="page-title">	Animal: recherche</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Animal</a> <span class="divider">/</span></li>
            <li class="active">Recherche</li>
        </ul>

<br />
<h3  class="alert-info" align="center"> Saisissez les 	&eacute;l&eacute;ments de recherche et cliquez sur "valider"...</h3>
<form class="form-horizontal" method="post" action="<?php echo $this->url();  ?>" enctype="multipart/form-data">
<div style="position: static; width: 98%; margin: auto;">
	<table style="background-color : #eeeeee; width: 98%" class="table-bordered" ><tr>
    <?php
    $i = 0;
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
       
        ?>
        <?php if( $elementName != 'photo' && $elementName != 'address_farmer' && $elementName !='rank_farmer'
        	&& $elementName !='registration_date'): ?>

        	<?php 	$i++; ?>
        		<?php  if($i%2 == 0) echo '</tr><tr>'; ?>
       		
	          
		            <td width="22%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
		            	<?php if ($element->getType() != 'Zend_Form_Element_Button'&& $element->getType() != 'Zend_Form_Element_File'): ?>
		                        <?php echo $element->getLabel(); ?>                        
		                <?php endif; ?>
		                
	                
		            </td>
	            	<td width="22" align="left">
		            	<?php if($element->getType() != 'Zend_Form_Element_File'):?>
		                <?php echo $element->renderViewHelper(); ?>
		                <?php endif; ?>
		                
		                
		               
		                <?php if ($errors): ?>
		                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
		                <?php endif; ?>
	                
		            </td>
	 <?php endif; ?>
	 
       
     <?php  endforeach; ?>
      </tr></table>
        <br/>
        <div class="row">
      <div class="span7"></div>
        <button class="btn btn-success" type="submit">Valider</button>
        <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'animal'), null, true); ?>">Annuler</a>
       </div>
  </div>
  

</form>



<h3 style="text-align:center" class="alert-success">R&eacute;sultats :</h3>


 <form method="post" action="<?php echo $this->url(array('controller' => 'animal', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<div style="margin-left:1em; margin-right:1em;">
<table width="100%" border="1" style="border-collapse:collapse" cellspacing="0" 
    cellpadding="3">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">ID Animal
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('fk_id_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Identifiant Eleveur
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_id_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_id_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('fk_animaltype' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Type d'animal
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('photo_left' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">VUE GAUCHE
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_left', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_left', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('photo_right' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">VUE DROITE 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_right', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_right', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('photo_front' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">VUE FACE 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_front', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'photo_front', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th><span class="label label-inverse">Signes particuliers</span></th>
            <th style="text-align: center;" ><span class="label label-inverse">Actions</span></th>
            
            
        </tr>
    </thead>
    
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
           
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->id ?>" /></td>
            <?php if($row->isstolen) {?>
            <td align="center"><blink title="<?php echo $row->animal_id; ?> :bete signalee comme volee" style="color:red"><?php echo substr($row->animal_id,9); ?></blink></td>
            <?php } else {?> 
             <td title="<?php echo $row->animal_id; ?>" align="center"><?php echo substr($row->animal_id,9); ?></td>
            <?php }?>
            <td align="center"><?php echo $row->fk_id_farmer; ?></td>
            <td align="center"><?php echo $row->fk_animaltype; ?></td>
            <td align="center"><a class="black" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'displayanimal', 'photo' => $row->photo_left), null, true); ?>">VUE GAUCHE</a>-<a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'updatephotoleft', 'id' => $row->animal_id), null, true); ?>">
                                                                   <?php if ($row->photo_left == "no_photo.png"){?><i class="icon-plus" ></i><?php } else {?><i class="icon-pencil"></i><?php }?> </a></td>
            <td align="center"><a class="black" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'displayanimal', 'photo' => $row->photo_right),null, true); ?>">VUE DROITE</a>-<a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'updatephotoright', 'id' => $row->animal_id), null, true); ?>">
                                                                   <?php if ($row->photo_right == "no_photo.png"){?><i class="icon-plus" ></i><?php } else {?><i class="icon-pencil"></i><?php }?> </a></td>
            <td><a class="black" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'displayanimal', 'photo' => $row->photo_front),null, true); ?>">VUE FACE</a>-<a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'updatephotofront', 'id' => $row->animal_id), null, true); ?>">
                                                                   <?php if ($row->photo_front == "no_photo.png"){?><i class="icon-plus" ></i><?php } else {?><i class="icon-pencil"></i><?php }?></a></td>
            <td align="center"><a  href="#" class="pop black" data-content="<?php echo $row->comment; ?> "data-original-title="Signes particuliers"><i class="icon-info-sign"></i></a>&nbsp;-<a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'updatecomment', 'id' => $row->animal_id), null, true); ?>">     
            
                                                                  <?php if ($row->comment == "R.A.S"){?><i class="icon-plus" ></i><?php } else {?><i class="icon-pencil"></i><?php }?> </a></td>
            <td align="center"><a title="supprimer" onclick="return confirm('Confirmer la suppression?');" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'delete', 'del_id' => $row->animal_id,'animal_type'=>$row->fk_animaltype,'id_farmer'=>$row->fk_id_farmer), null, true); ?>"><i class="icon-trash"></i></a>
                     <?php if ($row->isstolen) {?>
                        -<a title="signaler comme retrouve(e)" onclick="return confirm('Signaler comme retrouve(e)?');" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'unwarn', 'animal_id' => $row->animal_id,'id_farmer'=>$row->fk_id_farmer,'animal_type'=>$row->fk_animaltype), null, true); ?>"><i class="icon-ok"></i></a>
                     <?php } else {?>   
                        -<a title="signaler comme vole(e)" onclick="return confirm('Signaler comme vole(e)?');" href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'warn', 'animal_id' => $row->animal_id,'id_farmer'=>$row->fk_id_farmer,'animal_type'=>$row->fk_animaltype), null, true); ?>"><i class="icon-warning-sign"></i></a>
                      <?php }?></td>
       
        </tr>
<?php endforeach; ?>
    </tbody>
</table><br />
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');?>
</div>
</form>




</div>

