<?php //$this->headTitle('Login'); ?>
<?php //echo $this->form->setAction($this->url()); ?>
<?php $form= $this->form; ?>


<div id="logo" style="text-align:center;">
	
	<p><img src="<?php echo $this->baseUrl()."/img_logo/daral_logo.gif";?>" alt="logo Daral"/ class="img-circle" ></p>
	<h3>La technologie au service de l'elevage</h3>

</div>

<br/><br/>

	<!-- MAIN CONTENT -->
	<div id="content">
	
		
		<form class="form-horizontal" method="post" action="<?php echo $this->url();  ?>" enctype="multipart/form-data">
<div style="position: static; width: 45%; margin: auto;">
	<table style="background-color : #eeeeee; width: 90%" class="table-bordered" ><tr>
    <?php
    $i = 1;
    
   
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        $i++;
        ?>
        <?php if($i%2 == 1) echo '</tr><tr>'; ?>
	           
	            <td width="25%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
            	<?php if ($element->getType() != 'Zend_Form_Element_Button'&& $element->getType() != 'Zend_Form_Element_File'): ?>
                        <?php echo $element->getLabel(); ?>                        
                <?php endif; ?>
                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
                <?php echo "Photo: "; ?>
                <?php endif; ?>
                
	            </td>
            	<td width="25%" align="left">
            	<?php if($element->getType() != 'Zend_Form_Element_File'):?>
                <?php echo $element->renderViewHelper(); ?>
                <?php endif; ?>
                
                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
                <?php echo $this->form->photo; ?>
                <?php endif; ?>
                
                
               
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                
	            </td>
        <?php
        endforeach;
        ?>
        </tr></table>
        <br/>
        <div class="row">
        <div class="span3"></div>
      
        <button class="btn btn-success" type="submit">CONNEXION</button>
        <br/>
        </div>
  </div>
  

</form>
		
	</div> <!-- end content -->

