<?php if ($this->pageCount): ?>

<?php /*$total_pages=count($this->pagesInRange)*/
      $total_pages=$this->pageCount;
      $page_arr=$this->pagesInRange; 
     ?>

<div class="paginationControl">
<i>Page <?php echo $this->current;?> de <?php echo $total_pages;?> &nbsp; &nbsp; </i>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
 <!-- First page link -->
  <a class="black" href="<?php echo $this->url($_GET + array('page' => '1')) ?>">&lt; &lt; &nbsp; &nbsp; </a>
  
  <a  class="black" href="<?php echo $this->url($_GET + array('page' => $this->previous)); ?>">
    &lt; Pr&eacute;c&eacute;dent
  </a> |

<?php endif; ?>
 

 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a   class="black" href="<?php echo $this->url($_GET + array('page' => $this->next)); ?>">
   | Suivant &gt;
  </a>
<!-- Last page link -->
<a class="black" href="<?php echo $this->url($_GET + array('page'=>$total_pages))?>"> &nbsp; &nbsp; &gt; &gt; &nbsp; &nbsp; </a>
<?php endif; ?>
</div>
<?php endif; ?>