<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>

 <li class="active"> <a href="<?php echo $this->url($_GET + array('page' => $this->previous)); ?>">
&lt; &lt;  </a></li> 
<?php else: ?>
  <li class="disabled"><a href="#"> &lt; &lt;</a></li> 
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li class="active"><a href="<?php echo $this->url($_GET + array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a></li> 
  <?php else: ?>
    <li class="disabled"><a href="#"><?php echo $page; ?> </a></li>
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li class="active"><a href="<?php echo $this->url($_GET + array('page' => $this->next)); ?>">
    &gt; &gt; 
  </a></li>
<?php else: ?>
  <li class="disabled"><a href="#">&gt; &gt; </a></li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>