<?php
$tableDaral = new Application_Model_Daral_DbTable();
$tableAnimaltype = new Application_Model_Animaltype_DbTable();
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>

<div style="text-align:right">
<a href="<?php echo $this->url(array('controller' => 'daral-stat-animal', 'action' => 'index'), null, true); ?>">Reset Filters</a>
- <a href="<?php echo $this->url(array('controller' => 'daral-stat-animal', 'action' => 'create'), null, true); ?>">Add New</a></div><br />

<form method="get" action="<?php echo $this->url(array('controller' => 'daral-stat-animal', 'action' => 'index'), null, true); ?>">
<div>
Search for: <input type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" /> in 
<?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
  'all' => 'All',
  'fk_daral_name' => 'Fk Daral Name',
  'fk_animaltype' => 'Fk Animal Type',
)); ?>
<input type="submit" value="Go" />
</div>
</form>

<form method="post" action="<?php echo $this->url(array('controller' => 'daral-stat-animal', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<table width="100%" border="1" style="border-collapse:collapse" cellspacing="0" 
    cellpadding="3">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Id 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'desc')); ?>'>&#x25BC;</a>
                
            </th>
            <th<?php if ('fk_daral_name' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Fk Daral Name 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_daral_name', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_daral_name', '_so' => 'desc')); ?>'>&#x25BC;</a>
                <?php
    echo $this->formSelect('fk_daral_name', $this->paramfk_daral_name, array('onchange' => 'updateFilters(\'fk_daral_name\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableDaral->fetchPairs());
?>
            </th>
            <th<?php if ('fk_animaltype' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Fk Animal Type 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'desc')); ?>'>&#x25BC;</a>
                <?php
    echo $this->formSelect('fk_animaltype', $this->paramfk_animaltype, array('onchange' => 'updateFilters(\'fk_animaltype\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableAnimaltype->fetchPairs());
?>
            </th>
            <th<?php if ('total_animaltype' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Total Animal Type 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'total_animaltype', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'total_animaltype', '_so' => 'desc')); ?>'>&#x25BC;</a>
                
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Id 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'desc')); ?>'>&#x25BC;</a>
                
            </th>
            <th<?php if ('fk_daral_name' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Fk Daral Name 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_daral_name', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_daral_name', '_so' => 'desc')); ?>'>&#x25BC;</a>
                <?php
    echo $this->formSelect('fk_daral_name', $this->paramfk_daral_name, array('onchange' => 'updateFilters(\'fk_daral_name\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableDaral->fetchPairs());
?>
            </th>
            <th<?php if ('fk_animaltype' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Fk Animal Type 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'desc')); ?>'>&#x25BC;</a>
                <?php
    echo $this->formSelect('fk_animaltype', $this->paramfk_animaltype, array('onchange' => 'updateFilters(\'fk_animaltype\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableAnimaltype->fetchPairs());
?>
            </th>
            <th<?php if ('total_animaltype' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Total Animal Type 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'total_animaltype', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'total_animaltype', '_so' => 'desc')); ?>'>&#x25BC;</a>
                
            </th>
            <th>Actions</th>
        </tr>
    </tfoot>
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->id; ?>" /></td>
            <td align="right"><?php echo $row->id; ?></td>
            <td><?php     $linkedRow = $tableDaral->find($row->fk_daral_name)->current();
    if ($linkedRow) {
        echo $linkedRow->getZodekenAutoLabel();
    } else {
        echo $linkedRow->fk_daral_name, ' (unlinked)';
    } ?></td>
            <td><?php     $linkedRow = $tableAnimaltype->find($row->fk_animaltype)->current();
    if ($linkedRow) {
        echo $linkedRow->getZodekenAutoLabel();
    } else {
        echo $linkedRow->fk_animaltype, ' (unlinked)';
    } ?></td>
            <td align="right"><?php echo $row->total_animaltype; ?></td>
            <td align="center"><a href="<?php echo $this->url(array('controller' => 'daral-stat-animal', 'action' => 'update', 'id' => $row->id), null, true); ?>">Edit</a> 
    - <a onclick="return confirm('Confirm deletion!');" href="<?php echo $this->url(array('controller' => 'daral-stat-animal', 'action' => 'delete', 'del_id' => $row->id), null, true); ?>">Delete</a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table><br />
<input type="submit" value="Delete Selected Rows" />
</form>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');