<?php
$this->headTitle('Ajout eleveur');
$form = $this->form;
$tableCategorie = new Application_Model_Categorie_DbTable();
$categories= $tableCategorie->displayCategories();
?>

<script>
	$(function() {
		$( "#birthdate_farmer" ).datepicker();
	});

	

	$(function (){
		   $(".pop").popover({placement:'bottom'}); 
		});
	
</script>
<div class="content">	
<div class="header">
   <h1 class="page-title" >Inscription</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Eleveurs</a> <span class="divider">/</span></li>
            <li class="active">Inscription</li>
        </ul>
<br/> <br/>
<form class="form-horizontal" method="post" action="<?php echo $this->url();  ?>" enctype="multipart/form-data">
<div style="position: static; width: 90%; margin: auto;">
	<table style="background-color : #eeeeee; width: 90%" class="table-bordered" ><tr>
    <?php
    $i = 1;
    
   
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        $i++;
        ?>
        <?php if($i%2 == 0) echo '</tr><tr>'; ?>
	           
	            <td width="25%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
            	<?php if ($element->getType() != 'Zend_Form_Element_Button'&& $element->getType() != 'Zend_Form_Element_File'): ?>
                        <?php echo $element->getLabel(); ?>                        
                <?php endif; ?>
                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
                <?php echo "Photo: "; ?>
                <?php endif; ?>
                
	            </td>
            	<td width="25%" align="left">
            	<?php if($element->getType() != 'Zend_Form_Element_File'):?>
                <?php echo $element->renderViewHelper(); ?>
                <?php endif; ?>
                
                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
                <?php echo $this->form->photo; ?>
                <?php endif; ?>
                
                
               
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                
	            </td>
        <?php
        endforeach;
        ?>
                                                         
                                                                                    
                                                                        
                                                                                     
                                                                                      
                                                                     
                                                                     
                                                                     
        </tr></table>
        <div>
        <p>
        ( ? )
        <?php foreach ($categories as $categorie): ?>
        <?php echo $categorie; echo " | "?>
        <?php endforeach; ?>
         </p>
        </div>
        <br/>
        
        
        <div class="row">
       
      <div class="span6"></div>
        <button class="btn btn-success" type="submit">Valider</button>
        <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'farmer'), null, true); ?>">Annuler</a>
       </div>
  </div>
  

</form>


</div>
    