<?php
$this->headTitle('Ajout eleveur');
$form = $this->form;
?>

<script>
	$(function() {
		$( "#birthdate_farmer" ).datepicker();
	});
</script>
<div class="content">
<div class="page-header">
   <h3>Inscription</h3>
</div>

<form class="form-horizontal" method="post" action="<?php echo $this->url(); ?>" enctype="multipart/form-data">
<div style="position: static; width: 90%; margin: auto;">
	<table style="background-color : #eeeeee; width: 90%" class="table-bordered" ><tr>
    <?php
    $i = 1;
    
   
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        $i++;
        ?>
        <?php if($i%2 == 1) echo '</tr><tr>'; ?>
	           
	            <td width="25%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
            	<?php if ($element->getType() != 'Zend_Form_Element_Button'&& $element->getType() != 'Zend_Form_Element_File'): ?>
                        <?php echo $element->getLabel(); ?>                        
                <?php endif; ?>
                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
                <?php echo "Photo: "; ?>
                <?php endif; ?>
                
	            </td>
            	<td width="25%" align="left">
            	<?php if($element->getType() != 'Zend_Form_Element_File'):?>
                <?php echo $element->renderViewHelper(); ?>
                <?php endif; ?>
                
                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
                <?php echo $this->form->photo; ?>
                <?php endif; ?>
                
                
               
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                <?php if ('submit' == $elementName): ?>
                    <a class="btn" href="<?php echo $this->url(array('controller' => 'farmer'), null, true); ?>">Annuler</a>
                <?php endif; ?>
	            </td>
        <?php
        endforeach;
        ?>
        </tr></table>
  </div>

</form>
</div>    