<?php
error_reporting(E_ALL);
?>

<div class="content">	
<div class="header">
   <h1 class="page-title" >Inscription </h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Eleveurs</a> <span class="divider">/</span></li>
            <li class="active">Inscrire</li>
        </ul>

<?php 
$IDCard_path = $this->IDCard_path;
$id_farmer=$this->id_farmer;
$tableFarmer = new Application_Model_Farmer_DbTable_Farmer();
$op_syst = $tableFarmer->getOS();

if($op_syst=='WINDOWS')
{$name= substr(strrchr($IDCard_path,"\\"),1,20);}
else
{$name= substr(strrchr($IDCard_path,"/"),1,20);}	

?>


         <div class="alert alert-success "><h3 align="center">L'&eacute;leveur <?php echo $this->firstname.' '.$this->lastname;?> a bien &eacute;t&eacute; enregistr&eacute;.</h3></div>
         <br/>
      
      
         <div align="center"><img src="<?php echo $this->baseUrl()?>/image/<?php echo $name; ?>" width = "400 " height = "170 "  alt="photo" class ="thumbnail "/></div>
      
      
      <br/>

 <div align="center">
 <a class="btn" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>"><i class=" icon-chevron-left"></i> Retourner &agrave; la liste</a>
 <a target="_blank" class="btn btn-success" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'printcard','id'=>$id_farmer), null, true); ?>"><i class="icon-print"></i>Imprimer </a>
 <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'cheptel', 'action' => 'add','id'=>$id_farmer), null, true); ?>"><i class=" icon-plus icon-white"></i> Ajouter Cheptel</a>
</div>
</div>