<?php 
$farmer = new Application_Model_Farmer_DbTable_Farmer(); 
$cheptel= new  Application_Model_Cheptel_DbTable_Cheptel();
?>   
     
<div class="row">
  <div class="span7 "></div>
  <div><img src="<?php echo $this->baseUrl()?>/image/<?php echo $this->id; ?>.png" width = "400 " height = "170 "  alt="photo" class ="thumbnail "/></div>
</div>
      
<br/>

<?php 

  $farmer_cheptel=$cheptel->getFarmerCheptel($this->id);
?>
 <p><b>CHEPTEL: </b></p>
<?php 
 if($farmer_cheptel!=null) 
 {
     foreach ($farmer_cheptel as $row)
    {
  	echo $row['fk_animal_type'];
  	echo ": ";
  	echo $row['total_animal_type'];
  	echo "<br/>";
    }
 }
 
 else 
 {
 	echo "Aucun cheptel enregistre";
 }
?>

<br/>

<p><b>INFORMATIONS PERSONNELLES:</b></p>

<?php 
$farmer_info=$farmer->getFarmer($this->id);
?>
  <ul>
   <li>Date d'inscription:<?php echo " ".$farmer_info['registration_date']; ?></li>
   <li>Categorie:  <?php echo " ".$farmer_info['categorie']; ?></li>
   <li>Daral d'appartenance: <?php echo " ".$farmer_info['daral_actuel']; ?> </li>
   <li>No d'identification nationale: <?php echo " ".$farmer_info['national_id']; ?> </li>
   <li>Telephone: <?php echo " ".$farmer_info['phone_farmer']; ?></li>
   <li>Adresse: <?php  echo " ".$farmer_info['address_farmer']?></li>
   <li>Date de naissance: <?php echo " ".$farmer_info['birthdate_farmer']; ?></li>
   <li>Lieu de naissance: <?php echo " ".$farmer_info['birthplace_farmer']; ?></li>
  </ul>

