<?php 
$farmer = new Application_Model_Farmer_DbTable_Farmer(); 
$cheptel= new  Application_Model_Cheptel_DbTable_Cheptel();
?>   
<div class="content" >
<div class="header">
   <h1 class="page-title" >Profil Eleveur</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Eleveurs</a> <span class="divider">/</span></li>
            <li class="active">Profil Eleveur </li>
        </ul>
        
<div align="center"><img src="<?php echo $this->baseUrl()?>/image/<?php echo $this->id; ?>.png" width = "400 " height = "170 "  alt="photo" class ="thumbnail "/></div>
        
<div align="center">
  <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>"><i class="icon-chevron-left"></i>Retourner &agrave; la liste </a>
  <a target="_blank" class="btn btn-success" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'printcard','id'=>$this->id), null, true); ?>"><i class="icon-print"></i>Imprimer </a>
</div>  
<br/>

      

<?php 

  $farmer_cheptel=$cheptel->getFarmerCheptel($this->id);
?>
<hr>
<div class="container-fluid">
<div class="row-fluid">
<div class="span5">
 <p><b>CHEPTEL: </b></p>
<?php 
 if($farmer_cheptel!=null) 
 {
     foreach ($farmer_cheptel as $row)
    {
    $animal_type=$row['fk_animaltype'];	
  	echo $row['fk_animaltype'];
  	echo ": ";
  	echo $row['total_animaltype'];
  	?><span>&nbsp;</span><a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'index', 'fk_id_farmer' => $this->id,'fk_animaltype'=>$animal_type), null, true); ?>"><i class="icon-zoom-in"></i></a><br/><?php 
    }
 }
 
 else 
 {
 	echo "Aucun cheptel enregistre";
 }
?>
  <br>
  <a class="btn btn-success" href="<?php echo $this->url(array('controller' => 'cheptel', 'action' => 'add','id'=>$this->id), null, true); ?>"><i class="icon-plus icon-white"></i>Ajouter des animaux</a>
</div>
<div class="span7" style="border-left: 1px solid gray;">
<div style="margin-left:1em">
<p><b>INFORMATIONS PERSONNELLES:</b></p>

<?php 
$farmer_info=$farmer->getFarmer($this->id);
?>
  <ul>
   <li>Date d'inscription:<?php echo " ".$farmer_info['registration_date']; ?></li>
   <li>Cat&eacute;gorie:  <?php echo " ".$farmer_info['categorie']; ?></li>
   <li>Daral d'appartenance: <?php echo " ".$farmer_info['daral_actuel']; ?> </li>
   <li>No d'identification nationale: <?php echo " ".$farmer_info['national_id']; ?> </li>
   <li>T&eacute;l&eacute;phone: <?php echo " ".$farmer_info['phone_farmer']; ?></li>
   <li>Adresse: <?php  echo " ".$farmer_info['address_farmer']?></li>
   <li>Date de naissance: <?php echo " ".$farmer_info['birthdate_farmer']; ?></li>
   <li>Lieu de naissance: <?php echo " ".$farmer_info['birthplace_farmer']; ?></li>
  </ul>
  
  <a class="btn btn-success" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'edit','id'=>$this->id), null, true); ?>"><i class="icon-pencil icon-white"></i>Mettre &agrave; jour les infos</a>
</div>
</div>
</div>
</div>
</div>
