<div class="content">
<div class="header">
  <h1 class="page-title">Eleveurs: mise &agrave; jour des infos</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Eleveurs</a> <span class="divider">/</span></li>
            <li class="active">Mise &agrave; jour des infos</li>
        </ul>
        
        
		    <div  align="center" class="alert alert-info" >
		      <h3> Veuillez d&eacute;finir le mode de mise &agrave; jour</h3>
		    </div>
		    
		    <div align="center">
		     <a class="btn" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'nophotoedit','id'=>$this->id), null, true); ?>">SANS option de mise &agrave; jour de la photo </a> &nbsp; &nbsp;
             <a class="btn" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'selectphotoeditoption','id'=>$this->id), null, true); ?>"><i class="icon-picture"></i> &nbsp; AVEC option de mise &agrave; jour de la photo</a>
		   </div>
			

</div>
