<?php
$this->headTitle('Gestion des eleveurs');
$tableCategorie = new Application_Model_Categorie_DbTable();
$tableDaral = new Application_Model_Daral_DbTable();
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}


</script>

<script>

$(function (){
	   $(".pop").popover(); 
	});
</script>
    


<div class = "content"  >
<div class="header">
  <h1 class="page-title">Liste des eleveurs</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Eleveurs</a> <span class="divider">/</span></li>
            <li class="active">Liste</li>
        </ul>

<div style="float:right; margin-top: 1em;margin-right:1em;">
 <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>"><i class=" icon-refresh icon-white"></i> Actualiser</a>
    <!--  ****  changed 'action'=>'create' into 'action'=>'add' ***  -->
 <a class="btn btn-success" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'add'), null, true); ?>"><i class="icon-plus icon-white"></i> Inscrire</a>
    <!--  ********************************************************** -->
 </div> <br />

<form method="get" action="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>">
<div style="margin-left:1em;">
Rechercher: <input class="input-large search-query" placeholder="Mots cles..." type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" /> &nbsp dans &nbsp
<?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
  'all' => '-------------Tout------------',
  'id_farmer' => 'Identifiant',
  'firstname_farmer' => 'Prenom',
  'lastname_farmer' => 'Nom',
  'national_id' => 'Identification nationale',
  'address_farmer' => 'Adresse',
  'phone_farmer'=>'Telephone',
  //'daral_originel' => 'Daral Originel',
  'daral_actuel' => 'Daral d\'appartenance',
  
  //'birthplace_farmer' => 'Birthplace Farmer',
  'id_localite' => 'Localite',
)); ?> &nbsp
<button class="btn" type="submit"><i class="icon-search"></i>Rechercher</button>
</div>
</form>

<form method="post" action="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<div style="margin-left:1em; margin-right:1em;">
<table class="table table-bordered table-condensed " >
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
           
            <th style="text-align: center;" <?php if ('id_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
               <span class="label label-inverse"> Indentifiant 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
			<th style="text-align: center;" <?php if ('firstname_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Prenom
                <a href='<?php echo $this->url($_GET + array('_sf' => 'firstname_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'firstname_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th style="text-align: center;" <?php if ('lastname_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Nom 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'lastname_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'lastname_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th style="text-align: center;" <?php if ('categorie' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Categorie
                <a href='<?php echo $this->url($_GET + array('_sf' => 'categorie', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'categorie', '_so' => 'desc')); ?>'>&#x25BC;</a>
				</span> 
                
            </th>
            <th style="text-align: center;" <?php if ('national_id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Identification nationale
                <a href='<?php echo $this->url($_GET + array('_sf' => 'national_id', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'national_id', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th style="text-align: center;" <?php if ('address_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Adresse
                <a href='<?php echo $this->url($_GET + array('_sf' => 'address_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'address_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th style="text-align: center;">
                <span class="label label-inverse">Telephone</span> 
            </th>
           
            <th style="text-align: center;" <?php if ('daral_actuel' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Daral d'appartenance
                <a href='<?php echo $this->url($_GET + array('_sf' => 'daral_actuel', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'daral_actuel', '_so' => 'desc')); ?>'>&#x25BC;</a>
				</span>
               
            </th>
            
           
            
            <th style="text-align: center;" ><span class="label label-inverse">Actions</span></th>
        </tr>
    </thead>
    
    <tbody>
 
<?php foreach ($this->paginator as $row): ?>
        
         <tr>
       
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->id_farmer; ?>" /></td>
            <td style="text-align: center;" ><?php echo $row->id_farmer; ?></td>
			<td style="text-align: center;" ><?php echo $row->firstname_farmer; ?></td>
            <td style="text-align: center;" ><?php echo $row->lastname_farmer; ?></td>
            <td style="text-align: center;" ><?php     $linkedRow = $tableCategorie->find($row->categorie)->current();
    if ($linkedRow) {
        echo $linkedRow->getZodekenAutoLabel();
    } else {
        echo $linkedRow->categorie, ' (unlinked)';
    } ?></td>
            <td style="text-align: center;" ><?php echo $row->national_id; ?></td>
            <td style="text-align: center;" ><?php echo $row->address_farmer; ?></td>
            <td style="text-align: center;" ><?php echo $row->phone_farmer; ?></td>
            <td style="text-align: center;" ><a href="#" class="pop" data-content="<?php echo $row->id_localite; ?> "data-original-title="Localite"><?php echo $row->daral_actuel; ?></a> </td>
            <td style="text-align: center;" >
             <a data-toggle="modal" data-target="#infos" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'displayfarmer', 'id' => $row->id_farmer), null, true); ?>" ><i class="icon-zoom-in"></i></a> 
           - <a href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'edit', 'id' => $row->id_farmer), null, true); ?>"><i class="icon-pencil"></i></a> 
           - <a onclick="return confirm('Confirm deletion!');" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'delete', 'del_id' => $row->id_farmer), null, true); ?>"><i class="icon-trash"></i></a></td>
   
    
     </tr>
     
<?php  endforeach; ?>
    </tbody>
</table><br />

<button class="btn btn-danger" type="submit"><i class=" icon-trash icon-white"></i> Supprimer</button>
</div>
</form>

 
    <div class="modal hide fade" id="infos">
  <div class="modal-header"> <a class="close" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>">×</a>
    <h3>Plus d'informations</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer"> <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>">Fermer</a> </div>
</div>





<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');
?>
</div>
