<?php
$this->headTitle('Gestion des eleveurs');
$tableCategorie = new Application_Model_Categorie_DbTable();
$tableDaral = new Application_Model_Daral_DbTable();
$form = $this->form;
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}


</script>

<script>

$(function (){
	   $(".pop").popover(); 
	});
</script>
    


<div class = "content"  >
<div class="header">
  <h1 class="page-title">	Eleveurs: recherche</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Eleveurs</a> <span class="divider">/</span></li>
            <li class="active">Recherche</li>
        </ul>

<br />
<h3 style="margin-left:2em">Saisissez les 	&eacute;l&eacute;ments de recherche et cliquez sur "valider"...</h3>
<form class="form-horizontal" method="post" action="<?php echo $this->url();  ?>" enctype="multipart/form-data">
<div style="position: static; width: 98%; margin: auto;">
	<table style="background-color : #eeeeee; width: 98%" class="table-bordered" ><tr>
    <?php
    $i = 0;
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
       
        ?>
        <?php if( $elementName != 'photo' && $elementName != 'address_farmer' && $elementName !='rank_farmer'
        	&& $elementName !='registration_date'): ?>

        	<?php 	$i++; ?>
        		<?php  if($i%2 == 1) echo '</tr><tr>'; ?>
       		
	          
		            <td width="22%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
		            	<?php if ($element->getType() != 'Zend_Form_Element_Button'&& $element->getType() != 'Zend_Form_Element_File'): ?>
		                        <?php echo $element->getLabel(); ?>                        
		                <?php endif; ?>
		                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
		                <?php echo "Photo: "; ?>
		                <?php endif; ?>
	                
		            </td>
	            	<td width="22" align="left">
		            	<?php if($element->getType() != 'Zend_Form_Element_File'):?>
		                <?php echo $element->renderViewHelper(); ?>
		                <?php endif; ?>
		                
		                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
		                <?php echo $this->form->photo; ?>
		                <?php endif; ?>
		               
		                <?php if ($errors): ?>
		                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
		                <?php endif; ?>
	                
		            </td>
	 <?php endif; ?>
	 
       
     <?php  endforeach; ?>
      </tr></table>
        <br/>
        <div class="row">
      <div class="span7"></div>
        <button class="btn btn-success" type="submit">Valider</button>
        <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'farmer'), null, true); ?>">Annuler</a>
       </div>
  </div>
  

</form>



<h3 style="text-align:center">R&eacute;sultats :</h3>

<form method="post" action="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<div style="margin-left:1em; margin-right:1em;">
<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
           
            <th style="text-align: center;" <?php if ('id_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
               <span class="label label-inverse"> Indentifiant 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
			<th style="text-align: center;" <?php if ('firstname_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Prenom
                <a href='<?php echo $this->url($_GET + array('_sf' => 'firstname_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'firstname_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th style="text-align: center;" <?php if ('lastname_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Nom 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'lastname_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'lastname_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th style="text-align: center;" <?php if ('categorie' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Categorie
                <a href='<?php echo $this->url($_GET + array('_sf' => 'categorie', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'categorie', '_so' => 'desc')); ?>'>&#x25BC;</a>
				</span> 
                
            </th>
            <th style="text-align: center;" <?php if ('national_id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Identification nationale
                <a href='<?php echo $this->url($_GET + array('_sf' => 'national_id', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'national_id', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th style="text-align: center;" <?php if ('address_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Adresse
                <a href='<?php echo $this->url($_GET + array('_sf' => 'address_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'address_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th style="text-align: center;">
                <span class="label label-inverse">Telephone</span> 
            </th>
           
            <th style="text-align: center;" <?php if ('daral_actuel' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Daral d'appartenance
                <a href='<?php echo $this->url($_GET + array('_sf' => 'daral_actuel', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'daral_actuel', '_so' => 'desc')); ?>'>&#x25BC;</a>
				</span>
               
            </th>
            
           
            
            <th style="text-align: center;" ><span class="label label-inverse">Actions</span></th>
        </tr>
    </thead>
    
    <tbody>
 
<?php foreach ($this->paginator as $row): ?>
        
         <tr>
       
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->id_farmer; ?>" /></td>
            <td><?php echo $row->id_farmer; ?></td>
			<td><?php echo $row->firstname_farmer; ?></td>
            <td><?php echo $row->lastname_farmer; ?></td>
            <td><?php     $linkedRow = $tableCategorie->find($row->categorie)->current();
    if ($linkedRow) {
        echo $linkedRow->getZodekenAutoLabel();
    } else {
        echo $linkedRow->categorie, ' (unlinked)';
    } ?></td>
            <td><?php echo $row->national_id; ?></td>
            <td><?php echo $row->address_farmer; ?></td>
            <td><?php echo $row->phone_farmer; ?></td>
            <td><a href="#" class="pop black" data-content="<?php echo $row->id_localite; ?> "data-original-title="Localite"><?php echo $row->daral_actuel; ?></a> </td>
            <td>
             <a href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'displayfarmer', 'id' => $row->id_farmer), null, true); ?>" ><i class="icon-zoom-in"></i></a> 
           - <a href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'edit', 'id' => $row->id_farmer), null, true); ?>"><i class="icon-pencil"></i></a> 
           - <a onclick="return confirm('Confirm deletion!');" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'delete', 'del_id' => $row->id_farmer), null, true); ?>"><i class="icon-trash"></i></a></td>
   
    
     </tr>
     
<?php  endforeach; ?>
    </tbody>
</table><br />

<button class="btn btn-danger" type="submit"><i class=" icon-trash icon-white"></i> Supprimer</button>
</div>
</form>

 
    <div class="modal hide fade" id="infos">
  <div class="modal-header"> <a class="close" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>">×</a>
    <h3>Plus d'informations</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer"> <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'index'), null, true); ?>">Fermer</a> </div>
</div>





<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');
?>
</div>
