<div class="content">
<div class="header">
  <h1 class="page-title">Eleveurs: inscription</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Eleveurs</a> <span class="divider">/</span></li>
            <li class="active">Inscrire</li>
        </ul>
        
        
		    <div  align="center" class="alert alert-info" >
		      <h3> Veuillez choisir la m&eacute;thode d'inscription</h3>
		    </div>
		    
		    <div align="center">
		     <a class="btn" href="<?php echo $this->url(array('controller' => 'jpegcam', 'action' => 'takepicture'), null, true); ?>"><i class="icon-camera"></i> &nbsp; Utiliser la Web Cam</a> &nbsp; &nbsp;
             <a class="btn" href="<?php echo $this->url(array('controller' => 'farmer', 'action' => 'add'), null, true); ?>"><i class="icon-picture"></i> &nbsp; Charger manuellement la photo</a>
		   </div>
			

</div>
