<?php
$tableLocalite = new Application_Model_Localite_DbTable();
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>
<div class="content">	
<div class="header">
   <h1 class="page-title" >Liste des Darals</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Daral</a> <span class="divider">/</span></li>
            <li class="active">Liste</li>
        </ul>


<div style="text-align:right">
<div class="pull-right" style="margin-right:1em">
<a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'daral', 'action' => 'index'), null, true); ?>"><i class="icon-refresh icon-white"></i>Actualiser</a>
</div>
</div>

<form method="get" action="<?php echo $this->url(array('controller' => 'daral', 'action' => 'index'), null, true); ?>">
<div style="margin-left:1em">
Rechercher: <input type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" /> &nbsp dans &nbsp 
<?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
  'all' => 'Tout',
  'id_localite' => 'Localite',
  'name' => 'Numero Daral',
)); ?>
<button class="btn btn-success" type="submit" /><i class="icon-search icon-white"></i>Rechercher</button>
</div>
</form>

<form method="post" action="<?php echo $this->url(array('controller' => 'daral', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<table width="97%" border="1" style="border-collapse:collapse; margin-left:1em; margin-right:1em;" cellspacing="0" 
    cellpadding="3">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            
            <th<?php if ('name' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                 <span class="label label-inverse">Numero Daral
                <a href='<?php echo $this->url($_GET + array('_sf' => 'name', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'name', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            
            <th<?php if ('id_localite' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Localite 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id_localite', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id_localite', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th><span class="label label-inverse">Actions</span></th>
        </tr>
    </thead>
    
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->id; ?>" /></td>
            <td><?php echo $row->name; ?></td>
            <td><?php echo $row->id_localite; ?></td>
            <td align="center"><a  href="<?php echo $this->url(array('controller' => 'daral', 'action' => 'display'), null, true); ?>" ><i class="icon-zoom-in"></i></a> </tr>
<?php endforeach; ?>
    </tbody>
</table><br />

</form>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');?>
</div>