<! DOCTYPE html >
<html>
<head>
<meta charset="utf-8" />
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.8.2.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery.ui.widget.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery.ui.datepicker.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery.ui.datepicker-fr.js"></script>

<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/jquery.ui.all.css') ?> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/smoothness/jquery-ui-1.9.1.custom.css') ?> 
<script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap.min.js"></script> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/bootstrap/css/bootstrap.css'); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/styles.css') ?>

</head>
<body>
	<div id="header" style="height: 30px;">

		
	</div>
	<div style="width: 95%; margin: auto;">
				<div>
			
		<?php echo $this->layout()->content ?>
		</div>
	</div>
</body>
</html>

