<! DOCTYPE html >
<html>
<head>
<meta charset="utf-8" />



<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.8.2.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery.ui.widget.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery.ui.datepicker.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/ui/jquery.ui.datepicker-fr.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/gmaps.js"></script>

<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/jquery.ui.all.css') ?> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/smoothness/jquery-ui-1.9.1.custom.css') ?> 
<script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap.min.js"></script> 
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/bootstrap/css/bootstrap.css'); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/styles.css') ?>



  
   
<script type="text/javascript">
var mapOptions = {
	    center: new google.maps.LatLng(37.7831,-122.4039),
	    zoom: 12,
	    mapTypeId: google.maps.MapTypeId.ROADMAP
	};

	new google.maps.Map(document.getElementById('map'), mapOptions);


</script>    
    


</head>


<body>


	
	<div class=""  style="width:95%;margin:auto;margin-top:1em;">
		<div class="navbar"> 
			
	<?php  $auth = Zend_Auth::getInstance();
	       $request = Zend_Controller_Front::getInstance()->getRequest();
           $controller = $request->getControllerName();
     ?>
	<?php if($auth->hasIdentity() || $controller=='auth') {?>				
	
		

		
		
	<?php echo $this->layout()->content ?>
		
	<?php }else { ?>	
	
	<div style="margin-left:2em;">
  <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'index'), null, true); ?>"><i class="icon-chevron-left"></i>Se connecter &agrave; DARAL</a>

  <br/>
	<?php }?>
		</div>
	</div>
	</div>
</body>
</html>
