<! DOCTYPE html >
<html>
<head>
<meta charset="utf-8" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('bootstrap/css/bootstrap.css')); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl('bootstrap/js/bootstrap.min.js')) ?> 



</head>
<body>
<div id="header" style="height: 30px;">
    
    <div style="float: right; margin-right:30px;">
        <?php echo $this->loggedInAs();?>
    </div>
</div>
<div style="width:95%;margin:auto;">
 <div class="navbar" >
  <?php echo $this->displayMenu();?>
 </div >
 
 <div >
 <?php echo $this->layout()->content ?>
 </div>
</div> 
</body>
</html>