
	<head>
		<!----------------------          CHART             ------------------------------->
		<!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Animal');
        data.addColumn('number', 'Nombre');
        <?php  
        $tableAnimaltype= new Application_Model_Animaltype_DbTable_Animaltype();
	    $tableLocalite = new Application_Model_Localite_DbTable();
        $animaltypes=$tableAnimaltype->get_animal_types(); 
        
        $i=0;
        $total=array();
        
        foreach ($animaltypes as $animaltype)
        {
        	$total[$i]=$tableLocalite->get_localite_animaltype_total($animaltype, $this->localite);
        	$i++;
        
                } ?>
        
        
                <?php $cols=$animaltypes;?>
                <?php $number=$total;
                      $data=''; ?>
          	
          	    <?php for( $m=0;$m<$i ;$m++){
                  	
                  	if($m==0){
                     $data.="['".$cols[$m]."',".$number[$m]."]";
                  	}
                  	else {
                  		$data.=",['".$cols[$m]."',".$number[$m]."]";
                     }
                   }
                   
                   ?>
              
        
                   data.addRows([<?php echo $data; ?> ]);
                
                
                       
                    
        
        // Set chart options
        var options = {'title':'Repartition des animaux',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
		
		<!----------------------       END   CHART             ------------------------------->
		
		
       <!-----------------  MAP  ------------------------->
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript">
		function initialize() {

			<?php 
			
			$row=$tableLocalite->get_localite_latlng($this->localite);
			$coord=$row['LatLng'];
			$LatLng="LatLng".$coord;?>
			var latlng = new google.maps.<?php echo $LatLng; ?>;
			var settings = {
				zoom: 11,
				center: latlng,
				mapTypeControl: true,
				mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
				navigationControl: true,
				navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
				mapTypeId: google.maps.MapTypeId.TERRAIN};
			
			var map = new google.maps.Map(document.getElementById("map_canvas"), settings);

			var markerOptions = {
				    position: new google.maps.<?php echo $LatLng; ?>
				};
			
				var marker = new google.maps.Marker(markerOptions);
				marker.setMap(map);
				var infoWindowOptions = {
					    content: '<?php echo "Localit&eacute; de ".$this->localite." (D&eacute;partement de ".$this->departement.")"; ?>'
					};

					var infoWindow = new google.maps.InfoWindow(infoWindowOptions);
					google.maps.event.addListener(marker,'click',function(e){
					  
					  infoWindow.open(map, marker);
					  
					});
			
		}
		</script>
		<!-----------------------          END     ---------------------------->
		
		
	</head>
	<body onload="initialize()">
	
	<?php 
	
	
	$vals = $tableLocalite->getLocaliteStats($this->localite);
	
	?>
	<div class="content">
	<div class="header">
   <h1 class="page-title" >Statistiques de la localit&eacute; de  <?php echo " ".$this->localite." ( d&eacute;partement de ".$this->departement.")"; ?></h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Statistiques</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Localit&eacute;</a> <span class="divider">/</span></li>
            <li class="active"><?php echo $this->localite; ?></li>
        </ul>
        
       <div style="margin-left: 1em"><a class="btn btn-info" href="javascript:history.back();">Retour</a></div>  
        
<div style="margin-left: 1em ;margin-right: 1em; padding-bottom:0.5em;">        
	<div class="row-fluid">
	 	<div class="block">

					<a href="#page-stats" class="block-heading" data-toggle="collapse">Dernieres Statistiques 
						</a>
					<div id="page-stats" class="block-body collapse in">

						<div class="stat-widget-container">
							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">
    
    
    							<?php $test=0;?>
    
									<?php echo $vals[0]; ?></p>
									<p class="detail">Eleveurs</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[1]; ?></p>
									<p class="detail">Animaux</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[2]; ?></p>
									<p class="detail">Notifications</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[3]; ?></p>
									<p class="detail">Cas de vol</p>
								</div>
							</div>

						</div>
					</div>
				</div>
	</div>
</div>
        <div class="row-fluid" style="margin-left:1em">
		  <div class="block span6" id="chart_div"></div>
		  <div class="block span6" id="map_canvas" style="width:400px; height:300px;margin-left:2em;"></div>
	    </div>
   </div>