<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		

		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript">
			function initialize() {
				var latlng = new google.maps.LatLng(14.646039720201001,  -15.426376342773438);
				var settings = {
					zoom: 6,
					center: latlng,
					mapTypeControl: true,
					mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
					navigationControl: true,
					navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
					mapTypeId: google.maps.MapTypeId.TERRAIN};
				var map = new google.maps.Map(document.getElementById("map_canvas"), settings);
				
			}
		</script>
		
		<!----------------------          CHART             ------------------------------->
		<!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Animal');
        data.addColumn('number', 'Nombre');
        <?php  
        $tableAnimaltype= new Application_Model_Animaltype_DbTable_Animaltype();
        $tableNational = new Application_Model_National_DbTable();
        $animaltypes=$tableAnimaltype->get_animal_types(); 
        
        $i=0;
        $total=array();
        
        foreach ($animaltypes as $animaltype)
        {
        	$total[$i]=$tableNational->get_national_animaltype_total($animaltype);
        	$i++;
        
                } ?>
        
        
                <?php $cols=$animaltypes;?>
                <?php $number=$total;
                      $data=''; ?>
          	
          	    <?php for( $m=0;$m<$i ;$m++){
                  	
                  	if($m==0){
                     $data.="['".$cols[$m]."',".$number[$m]."]";
                  	}
                  	else {
                  		$data.=",['".$cols[$m]."',".$number[$m]."]";
                     }
                   }
                   
                   ?>
              
        
                   data.addRows([<?php echo $data; ?> ]);
                
                
                       
                    
        
        // Set chart options
        var options = {'title':'Repartition des animaux',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
		
		<!----------------------       END   CHART             ------------------------------->
		
	</head>
	<body onload="initialize()">
	
	<?php 
	
	
	$vals = $tableNational->getNationalStats();
	
	?>
	<div class="content">
	<div class="header">
   <h1 class="page-title" >Statistiques Nationales</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Statistiques </a><span class="divider">/</span></li>
            <li class="active">Pays</li>
        </ul>
        <div style="margin-left: 1em"><a class="btn btn-info" href="javascript:history.back();">Retour</a></div>  
        
       
<div style="margin-left: 1em ;margin-right: 1em; padding-bottom:0.5em;">     

	<div class="row-fluid">
	 	<div class="block">
	 	

					<a href="#page-stats" class="block-heading" data-toggle="collapse">Dernieres Statistiques 
						</a>
					<div id="page-stats" class="block-body collapse in">

						<div class="stat-widget-container">
							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">
    
    
    							<?php $test=0;?>
    
									<?php echo $vals[0]; ?></p>
									<p class="detail">Eleveurs</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[1]; ?></p>
									<p class="detail">Animaux</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[2]; ?></p>
									<p class="detail">Notifications</p>
								</div>
							</div>

							<div class="stat-widget">
								<div class="stat-button">
									<p class="title">

									<?php echo $vals[3]; ?></p>
									<p class="detail">Cas de vol</p>
								</div>
							</div>

						</div>
					</div>
				</div>
	</div>
</div>
		<div class="row-fluid" style="margin-left:1em">
		  <div class="block span6" id="chart_div"></div>
		  <div class="block span6" id="map_canvas" style="width:400px; height:300px;margin-left:2em;"></div>
	    </div>			
		
	</div>
	
	</body>
</html>


