<?php
$this->headTitle('Modifier maladie');
$form = $this->form;
$tableUsers = new Application_Model_Users_DbTable();
?>

<script>
	$(function() {
		$( "#date" ).datepicker();
	});
</script>
	
<div class="content">	
<div class="header">
   <h1 class="page-title" >Modifier langue</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="<?php echo $this->url(array('controller' => 'maladie'), null, true); ?>" class="black">Liste des maladies</a><span class="divider">/</span></li>
            <li class="active">Modifier maladie</li>
        </ul>
<form class="form-horizontal" method="post" action="<?php echo $this->url(); ?>">
<div style="position: static; width: 90%; margin: auto;">
	<table style="background-color : #eeeeee; width: 90%" class="table-bordered" ><tr>
    <?php
    $i = 1;
    
   
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        $i++;
        ?>
        <?php if($i%2 == 1) echo '</tr><tr>'; ?>
	           
	            <td width="25%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
            	<?php if ($element->getType() != 'Zend_Form_Element_Button'): ?>
                        <?php echo $element->getLabel(); ?>
                <?php endif; ?>
	            </td>
            	<td width="25%" align="left">
                <?php echo $element->renderViewHelper(); ?>
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                
	            </td>
        <?php
        endforeach;
        ?>
        </tr></table>
         <br/>
        <div class="row">
      <div class="span7"></div>
        <button class="btn btn-success" type="submit">Valider</button>
        
        <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'maladie'), null, true); ?>">Annuler</a>
       </div>
  </div>

</form>
</div>    