<?php
$this->headTitle('Gestion du cheptel: enregistrement');
$form = $this->form;
?>


	


<div class="content">	
<div class="header">
   <h1 class="page-title" >Ajouter des animaux</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Cheptel</a> <span class="divider">/</span></li>
            <li class="active">Ajouter des animaux</li>
        </ul>

        
 <br>
    
<form class="form-horizontal" method="post" action="<?php echo $this->url();  ?>" enctype="multipart/form-data">
<div style="position: static; width: 90%; margin: auto;">
	<table style="background-color : #eeeeee; width: 90%" class="table-bordered" ><tr>
    <?php
    $i = 1;
    
   
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        $i++;
        ?>
        <?php if($i%2 == 1) echo '</tr><tr>'; ?>
	           
	            <td width="25%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
            	<?php if ($element->getType() != 'Zend_Form_Element_Button'&& $element->getType() != 'Zend_Form_Element_File'): ?>
                        <?php echo $element->getLabel(); ?>                        
                <?php endif; ?>
                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
                <?php echo "Photo: "; ?>
                <?php endif; ?>
                
	            </td>
            	<td width="25%" align="left">
            	<?php if($element->getType() != 'Zend_Form_Element_File'):?>
                <?php echo $element->renderViewHelper(); ?>
                <?php endif; ?>
                
                <?php if($element->getType() == 'Zend_Form_Element_File'):?>
                <?php echo $this->form->photo; ?>
                <?php endif; ?>
                
                
               
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                
	            </td>
        <?php
        endforeach;
        ?>
        </tr></table>
        <br/>
        <div class="row">
      <div class="span5"></div>
        <button class="btn btn-success" type="submit">Valider</button>
        <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'cheptel'), null, true); ?>">Annuler</a>
       </div>
  </div>
  

</form>
</div>