
<div class="content" >
<div class="header">

   <h1 class="page-title" >Ajouter des animaux</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Cheptel</a> <span class="divider">/</span></li>
            <li class="active">Ajouter des animaux</li>
        </ul>

        
 <br>
    <div class="alert alert-danger" style="margin-left:1em;margin-right:1em;">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>Mise &agrave; jour impossible!</h4>
    Le nombre maximal de b&ecirc;tes pour cet &eacute;leveur sera d&eacute;passe&eacute;...
    </div>
    
    <div style="margin-left: 1em"><a class="btn btn-info" href="javascript:history.back();">Retour</a></div>  
    
</div>
