
<div class="content" >
<div class="header">

   <h1 class="page-title" >Ajouter des animaux</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Cheptel</a> <span class="divider">/</span></li>
            <li class="active">Ajouter des animaux</li>
        </ul>

        
 <br>
    <div class="alert alert-danger" >
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4 align="center">Mise &agrave; jour impossible!</h4>
    <p align="center">Le nombre maximal de b&ecirc;tes pour cet &eacute;leveur sera d&eacute;pass&eacute;...</p>
    </div>
    
    <div align="center"><a class="btn btn-info" href="javascript:history.back();">Retour</a></div>  
    
</div>
