<?php
$this->headTitle('Gestion des eleveurs');
$tableCheptel = new Application_Model_Cheptel_DbTable_Cheptel();
$form = $this->form;
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}


</script>

<script>

$(function (){
	   $(".pop").popover(); 
	});
</script>
    


<div class = "content"  >
<div class="header">
  <h1 class="page-title">	Cheptel: recherche</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Cheptel</a> <span class="divider">/</span></li>
            <li class="active">Recherche</li>
        </ul>

<br />
<h3  class="alert-info" align="center"> Saisissez les 	&eacute;l&eacute;ments de recherche et cliquez sur "valider"...</h3>
<form class="form-horizontal" method="post" action="<?php echo $this->url();  ?>" enctype="multipart/form-data">
<div style="position: static; width: 98%; margin: auto;">
	<table style="background-color : #eeeeee; width: 98%" class="table-bordered" ><tr>
    <?php
    $i = 0;
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
       
        ?>
        <?php if( $elementName != 'photo' && $elementName != 'address_farmer' && $elementName !='rank_farmer'
        	&& $elementName !='registration_date'): ?>

        	<?php 	$i++; ?>
        		<?php  if($i%2 == 0) echo '</tr><tr>'; ?>
       		
	          
		            <td width="22%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
		            	<?php if ($element->getType() != 'Zend_Form_Element_Button'&& $element->getType() != 'Zend_Form_Element_File'): ?>
		                        <?php echo $element->getLabel(); ?>                        
		                <?php endif; ?>
		                
	                
		            </td>
	            	<td width="22" align="left">
		            	<?php if($element->getType() != 'Zend_Form_Element_File'):?>
		                <?php echo $element->renderViewHelper(); ?>
		                <?php endif; ?>
		                
		                
		               
		                <?php if ($errors): ?>
		                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
		                <?php endif; ?>
	                
		            </td>
	 <?php endif; ?>
	 
       
     <?php  endforeach; ?>
      </tr></table>
        <br/>
        <div class="row">
      <div class="span7"></div>
        <button class="btn btn-success" type="submit">Valider</button>
        <a class="btn btn-info" href="<?php echo $this->url(array('controller' => 'farmer'), null, true); ?>">Annuler</a>
       </div>
  </div>
  

</form>



<h3 style="text-align:center" class="alert-success">R&eacute;sultats :</h3>


 <form method="post" action="<?php echo $this->url(array('controller' => 'cheptel', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<div style="margin-left:1em; margin-right:1em;">
<table width="100%" border="1" style="border-collapse:collapse" cellspacing="0" 
    cellpadding="3">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            
            <th<?php if ('fk_id_farmer' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Identifiant eleveur
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_id_farmer', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_id_farmer', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('fk_animaltype' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Type d'animal
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'fk_animaltype', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th<?php if ('total_animaltype' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                <span class="label label-inverse">Total
                <a href='<?php echo $this->url($_GET + array('_sf' => 'total_animaltype', '_so' => 'asc')); ?>'>&#x25B2;</a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'total_animaltype', '_so' => 'desc')); ?>'>&#x25BC;</a>
                </span>
            </th>
            <th><span class="label label-inverse">Actions</span></th>
        </tr>
    </thead>
        <tbody>
        

<?php foreach ($this->paginator as $row): ?>
        <tr>
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->id; ?>" /></td>
            <td align="center"><?php echo $row->fk_id_farmer;?></td>
            <td align="center"><?php echo $row->fk_animaltype; ?></td>
            <td align="center"><?php echo $row->total_animaltype; ?></td>
            <!--  
            <td align="center"><a href="<?php// echo $this->url(array('controller' => 'cheptel', 'action' => 'update', 'id' => $row->id), null, true); ?>">Edit</a> 
    - <a onclick="return confirm('Confirm deletion!');" href="<?php //echo $this->url(array('controller' => 'cheptel', 'action' => 'delete', 'del_id' => $row->id), null, true); ?>">Delete</a></td>
        </tr>
        -->
        <td align="center"><a href="<?php echo $this->url(array('controller' => 'animal', 'action' => 'index', 'fk_id_farmer' => $row->fk_id_farmer,'fk_animaltype'=>$row->fk_animaltype), null, true); ?>"><i class="icon-zoom-in"></i></a> 
    
        </tr>
<?php  endforeach; ?>
    </tbody>
</table><br />
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');
?>
</div>
</form>





</div>
