
<div class="content" >
<div class="header">

   <h1 class="page-title" >Ajouter des animaux</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Mon Daral</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Cheptel</a> <span class="divider">/</span></li>
            <li class="active">Ajouter des animaux</li>
        </ul>

        
 <br>
    <div class="alert alert-success" style="margin-left:1em;margin-right:1em;">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4> Enrgistrement du cheptel r&eacute;ussie!</h4>
    </div>
    <div><p><?php $ids=$this->ids;?><p></div>
    <div style="margin-left: 1em">
      <a class="btn btn-info" href="javascript:history.back();">Retour</a>
      <a target="_blank" class="btn btn-success" href="<?php echo $this->url(array('controller' => 'cheptel', 'action' => 'printids','animal_ids'=>$ids), null, true); ?>"><i class="icon-print"></i>Imprimer la liste des identifiants </a>
     </div> 
    
</div>

