<?php
$this->headTitle('Modificaion Veterinaire: ' . 
    $this->row->getZodekenAutoLabel());
$form = $this->form;


?>
	<script>
	$(function() {
		$( "#Dateevenappr" ).datepicker();
	});
	</script>

<div class="content">	
<div class="header">
   <h1 class="page-title" >Mise a jour info veterinaire</h1>
</div>

        <ul class="breadcrumb">
            <li><a href="#" class="black">Contacts</a><span class="divider">/</span></li>
            <li><a href="#" class="black" >Veterinaire</a> <span class="divider">/</span></li>
            <li class="active">Mise a jour info</li>
        </ul>

<form class="form-horizontal" method="post" action="<?php echo $this->url(); ?>">
<div style="position: static; width: 90%; margin: auto;">
	<table style="background-color : #eeeeee; width: 90%" ><tr>
    <?php
    $i = 2;
    
   
    
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        $i++;
        ?>
        <?php if($i%2 == 1) echo '</tr><tr>'; ?>
	           
	            <td width="25%" align="right" class="control-group<?php if ($errors) echo ' error'; ?>">
            	<?php if ($element->getType() != 'Zend_Form_Element_Button'): ?>
                        <?php echo $element->getLabel(); ?>
                <?php endif; ?>
	            </td>
            	<td width="25%" align="left">
                <?php echo char($element->renderViewHelper()); ?>
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                <?php if ('submit' == $elementName): ?>
                    <a class="btn" href="<?php echo $this->url(array('controller' => 'veterinaire'), null, true); ?>">Annuler</a>
                <?php endif; ?>
	            </td>
        <?php
        endforeach;
        ?>
        </tr></table>
  </div>

</form>
</div>